apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  tolerations: 
    - key: spray
      value: mortein
      effect: NoSchedule