@Library('dev_lib') _

pipeline {
    agent { label 'master' }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                load 'vars.groovy'
                echo call()
            }
        }
    }
}
