apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
  initContainers:
  - name: init-busybox
    image: busybox
    command:
    - "sleep"
    - "20"

