apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/k8s-demo-app:v1.0
        envFrom:
        - configMapRef:
            name: mongo-config
        - secretRef:
            name: mysecret
        ports:
        - containerPort: 80
